import type { EditorGroup, EditorShape, EditorVisualProperties, ShapeType } from './types'

type ShapeIdentity = Pick<EditorShape, 'id' | 'type' | 'name' | 'groupId' | 'x' | 'y' | 'width' | 'height'>
type GroupIdentity = Pick<EditorGroup, 'id' | 'name' | 'shapeIds' | 'x' | 'y' | 'width' | 'height'>

const getDefaultFill = (type: ShapeType) => type === 'text' ? '#202020' : type === 'ellipse' ? '#9B7FE8' : '#5D8FF2'
const getDefaultGradientEnd = (type: ShapeType) => type === 'text' ? '#686868' : type === 'ellipse' ? '#5D8FF2' : '#9B7FE8'

const createVisualProperties = (
  transform: Pick<EditorVisualProperties, 'x' | 'y' | 'width' | 'height'>,
  fill: string,
  gradientEnd = '#9B7FE8',
): EditorVisualProperties => ({
  ...transform,
  rotation: 0,
  fill,
  fillType: 'solid',
  fillGradientStart: fill,
  fillGradientEnd: gradientEnd,
  fillGradientAngle: 90,
  fillOpacity: 1,
  fillVisible: true,
  fillPresent: true,
  outlineVisible: false,
  outlinePresent: false,
  outlineWidth: 1,
  outlineOffset: 0,
  outlineColor: '#000000',
  outlineOpacity: 1,
  borderVisible: false,
  borderPresent: false,
  borderWidth: 1,
  borderSides: 'all',
  borderColor: '#000000',
  borderOpacity: 1,
  shadowVisible: false,
  shadowPresent: false,
  shadowX: 0,
  shadowY: 8,
  shadowBlur: 18,
  shadowSpread: 0,
  shadowColor: '#000000',
  shadowOpacity: 0.18,
  innerShadowVisible: false,
  innerShadowPresent: false,
  innerShadowX: 0,
  innerShadowY: 2,
  innerShadowBlur: 3,
  innerShadowSpread: 0,
  innerShadowColor: '#000000',
  innerShadowOpacity: 0.2,
  opacity: 1,
  visible: true,
  locked: false,
})

export function createEditorShape(identity: ShapeIdentity): EditorShape {
  const fill = getDefaultFill(identity.type)
  return {
    ...createVisualProperties(identity, fill, getDefaultGradientEnd(identity.type)),
    ...identity,
    rotation: 0,
    radius: 0,
    smoothing: 0,
    independentCorners: false,
    radiusTopLeft: 0,
    radiusTopRight: 0,
    radiusBottomRight: 0,
    radiusBottomLeft: 0,
    text: identity.type === 'text' ? 'Type something' : '',
    fontSize: 24,
    fontWeight: 400,
    textAlign: 'left',
  }
}

export function createEditorGroup(identity: GroupIdentity, source?: EditorShape): EditorGroup {
  const fill = source?.fill ?? '#DDDDDD'
  return {
    ...createVisualProperties(identity, fill),
    ...identity,
    fillType: source?.fillType ?? 'solid',
    fillGradientStart: source?.fillGradientStart ?? fill,
    fillGradientEnd: source?.fillGradientEnd ?? '#9B7FE8',
    fillGradientAngle: source?.fillGradientAngle ?? 90,
    fillPresent: source?.fillPresent ?? true,
    outlineVisible: source?.outlineVisible ?? false,
    outlinePresent: source?.outlinePresent ?? false,
    outlineWidth: source?.outlineWidth ?? 1,
    outlineOffset: source?.outlineOffset ?? 0,
    outlineColor: source?.outlineColor ?? '#000000',
    outlineOpacity: source?.outlineOpacity ?? 1,
    borderVisible: source?.borderVisible ?? false,
    borderPresent: source?.borderPresent ?? false,
    borderWidth: source?.borderWidth ?? 1,
    borderSides: source?.borderSides ?? 'all',
    borderColor: source?.borderColor ?? '#000000',
    borderOpacity: source?.borderOpacity ?? 1,
    shadowVisible: source?.shadowVisible ?? false,
    shadowPresent: source?.shadowPresent ?? false,
    shadowX: source?.shadowX ?? 0,
    shadowY: source?.shadowY ?? 8,
    shadowBlur: source?.shadowBlur ?? 18,
    shadowSpread: source?.shadowSpread ?? 0,
    shadowColor: source?.shadowColor ?? '#000000',
    shadowOpacity: source?.shadowOpacity ?? 0.18,
    innerShadowVisible: source?.innerShadowVisible ?? false,
    innerShadowPresent: source?.innerShadowPresent ?? false,
    innerShadowX: source?.innerShadowX ?? 0,
    innerShadowY: source?.innerShadowY ?? 2,
    innerShadowBlur: source?.innerShadowBlur ?? 3,
    innerShadowSpread: source?.innerShadowSpread ?? 0,
    innerShadowColor: source?.innerShadowColor ?? '#000000',
    innerShadowOpacity: source?.innerShadowOpacity ?? 0.2,
  }
}

const hydrateVisualProperties = <T extends EditorVisualProperties>(target: T): T => ({
  ...target,
  fillType: target.fillType ?? 'solid',
  fillGradientStart: target.fillGradientStart ?? target.fill,
  fillGradientEnd: target.fillGradientEnd ?? '#9B7FE8',
  fillGradientAngle: target.fillGradientAngle ?? 90,
  fillOpacity: target.fillOpacity ?? 1,
  fillVisible: target.fillVisible ?? true,
  fillPresent: target.fillPresent ?? true,
  outlineVisible: target.outlineVisible ?? false,
  outlinePresent: target.outlinePresent ?? target.outlineVisible ?? false,
  outlineWidth: target.outlineWidth ?? 1,
  outlineOffset: target.outlineOffset ?? 0,
  outlineColor: target.outlineColor ?? '#000000',
  outlineOpacity: target.outlineOpacity ?? 1,
  borderVisible: target.borderVisible ?? false,
  borderPresent: target.borderPresent ?? target.borderVisible ?? false,
  borderWidth: target.borderWidth ?? 1,
  borderSides: target.borderSides ?? 'all',
  borderColor: target.borderColor ?? '#000000',
  borderOpacity: target.borderOpacity ?? 1,
  shadowVisible: target.shadowVisible ?? false,
  shadowPresent: target.shadowPresent ?? target.shadowVisible ?? false,
  shadowX: target.shadowX ?? 0,
  shadowY: target.shadowY ?? 8,
  shadowBlur: target.shadowBlur ?? 18,
  shadowSpread: target.shadowSpread ?? 0,
  shadowColor: target.shadowColor ?? '#000000',
  shadowOpacity: target.shadowOpacity ?? 0.18,
  innerShadowVisible: target.innerShadowVisible ?? false,
  innerShadowPresent: target.innerShadowPresent ?? target.innerShadowVisible ?? false,
  innerShadowX: target.innerShadowX ?? 0,
  innerShadowY: target.innerShadowY ?? 2,
  innerShadowBlur: target.innerShadowBlur ?? 3,
  innerShadowSpread: target.innerShadowSpread ?? 0,
  innerShadowColor: target.innerShadowColor ?? '#000000',
  innerShadowOpacity: target.innerShadowOpacity ?? 0.2,
  locked: target.locked ?? false,
})

export const hydrateEditorShape = (shape: EditorShape): EditorShape => ({
  ...hydrateVisualProperties(shape),
  groupId: shape.groupId ?? null,
  independentCorners: shape.independentCorners ?? false,
  smoothing: shape.smoothing ?? 0,
  radiusTopLeft: shape.radiusTopLeft ?? shape.radius ?? 0,
  radiusTopRight: shape.radiusTopRight ?? shape.radius ?? 0,
  radiusBottomRight: shape.radiusBottomRight ?? shape.radius ?? 0,
  radiusBottomLeft: shape.radiusBottomLeft ?? shape.radius ?? 0,
})

export const hydrateEditorGroup = (group: EditorGroup): EditorGroup => hydrateVisualProperties(group)
